# Project information
site_name: Java学习路线
site_url: https://hye2cs.github.io/Java-Learning/
site_author: ZYJ
site_description: >-
  Help you to learn Java.

# Repository
repo_name: hye2cs/Java-Learning/
repo_url: https://github.com/HYe2cS/Java-Learning
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 - 2020 ZYJ

# Configuration
theme:
  #  name: null
  #  custom_dir: material
  name: material
  # 404 page
  static_templates:
    - 404.html
  
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  
  
  # Default values, taken from mkdocs_theme.yml
  language: zh
  
  features: # 特性
    - navigation.expand #激活时，左侧栏将默认展开所有可折叠小节，因此用户不必手动执行此操作
    - navigation.instant #激活即时加载时，所有内部链接的点击将截获，并通过XHR发送，而无需完全重新加载页面
    - navigation.tabs # 激活选项卡时，顶级部分将呈现在大屏幕上标题下方的菜单层中（但当侧边栏隐藏时不会）
    - header.autohide #自动隐藏顶部，给阅读留下空间
  
  palette: # 调色板
    scheme: slate
    primary: orange
    accent: orange
  
  font: # 字体
    text: Roboto
    code: Roboto Mono
  
  # icon和徽标
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - search
#    - redirects: # 搜索重定向
#        redirect_maps:
#          extensions/admonition.md: reference/admonitions.md
#          extensions/codehilite.md: reference/code-blocks.md
#          extensions/footnotes.md: reference/footnotes.md
#          extensions/metadata.md: reference/meta-tags.md
#          extensions/permalinks.md: setup/setting-up-navigation.md #permalink
#          extensions/pymdown.md: reference/admonitions.md
#          plugins/revision-date.md: setup/adding-a-git-repository.md #revision-date
#          plugins/search.md: setup/setting-up-site-search.md
#          releases/4.md: upgrading.md #upgrading-from-4x-to-5x
#          releases/5.md: upgrading.md #upgrading-from-3x-to-4x
#          releases/changelog.md: changelog.md
#          setup/adding-social-links.md: setup/setting-up-the-footer.md
#          sponsorship.md: insiders.md
  - minify:
      minify_html: true

# Customization 定制图标指向链接
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/HYe2cS

#    - icon: fontawesome/brands/gitter
#      link: https://gitter.im/squidfunk/mkdocs-material
#    - icon: fontawesome/brands/docker
#      link: https://hub.docker.com/r/squidfunk/mkdocs-material/
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/squidfunk
#    - icon: fontawesome/brands/linkedin
#      link: https://linkedin.com/in/squidfunk/
#    - icon: fontawesome/brands/instagram
#      link: https://instagram.com/squidfunk

# Markdown扩展 Extensions
markdown_extensions:
  - admonition #告诫
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc: #目录
      permalink: true #标题title右边点击定位到顶部的按钮
  # 启用pymdownx支持
  - pymdownx.arithmatex: # 算术数
      generic: true
  - pymdownx.betterem: # 智能启用,它提供了两种模式来控制星号和下划线粗体和粗体语法：打开时智能，如果关闭时正常
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight # 代码高亮
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# 自带的代码高亮，并不好用
#hljs_languages:
#  - yaml
#  - rust
#  - Java

# Page tree 页面树
nav:
  - 怎样学Java:
      - 介绍: index.md
      - 学习方法和书籍: pre/0_1_学习方法和书籍.md
      - 已经过时的一些知识: pre/0_2_已经过时的一些知识.md
      - Java学习路线: pre/0_3_Java学习路线.md
      - 笔记目录: pre/0_4.md
  - 学习笔记:
      - 第一阶段：基础知识: notes/0_index_1.md
      #      - 第1部分_2周:
      - 1.1 Java程序设计概述: notes/1_基础知识_1_1.md
      - 1.2 Java程序设计环境: notes/1_基础知识_1_2.md
      - 1.3 Java的基础程序设计结构: notes/1_基础知识_1_3.md
      #      - 第2部分_2周:
      - 2.1 类和对象: notes/1_基础知识_2_1.md
      - 2.2 接口与抽象类: notes/1_基础知识_2_2.md
      - 2.3 lambda表达式与内部类: notes/1_基础知识_2_3.md
      - 2.4 发布和部署: notes/1_基础知识_2_4.md
      #      - 第3部分_1周:
      - 3.1 泛型: notes/1_基础知识_3_1.md
      - 3.2 集合: notes/1_基础知识_3_2.md
      #      - 第4部分_1周:
      - 4.1 异常与调试: notes/1_基础知识_4_1.md
      - 4.2 多线程: notes/1_基础知识_4_2.md
      - 第二阶段：Spring: notes/0_index_2.md
      #      - 第1部分_1周:
      - Maven: notes/2_Spring_1_1.md
      - 单元测试: notes/2_Spring_1_2.md
      #      - 第2部分_2周:
      - Spring Core: notes/2_Spring_2.md
      #      - 第3部分_2周:
      - HTTP协议: notes/2_Spring_3_1.md
      - JSON: notes/2_Spring_3_2.md
      - Servlet: notes/2_Spring_3_3.md
      #      - 第4部分_1周:
      - Spring_4: notes/2_Spring_4.md
      - 第三阶段：应用服务: notes/0_index_3.md
      #      - 第1部分_2周:
      - 应用服务_1_1: notes/3_应用服务_1_1.md
      - 应用服务_1_2: notes/3_应用服务_1_2.md
      #      - 第2部分_1周:
      - 应用服务_2_1: notes/3_应用服务_2_1.md
      - 应用服务_2_2: notes/3_应用服务_2_2.md
      #      - 第3部分_1周:
      - 应用服务_3_1: notes/3_应用服务_3_1.md
      - 应用服务_3_2: notes/3_应用服务_3_2.md
      #      - 第4部分_1周:
      - 应用服务_4: notes/3_应用服务_4.md
  - 文章集:
#      - test: ../src/code_in_book/v1ch02/Welcome/Welcome.java  not ok
      - 如何系统的自学Java语言: article/0_4_如何系统的自学Java语言.md
      - java11中关于javafx配置_IDEA踩坑实录: article/java11中关于javafx配置_IDEA踩坑实录.md
      - 原文转载-Java学习路线图: article/Java学习路线图.md
  - Changelog:
      - 其他的一些链接: changelog/0_5_链接集.md
      - 开发计划: changelog/TODO.md
      - testMarkdown: changelog/test.md

# Google Analytics
google_analytics:
  - UA-180490240-1
  - auto